### Ping Test
GET http://127.0.0.1:8000/api/ping
Accept: application/json
#
###
GET http://127.0.0.1:8000/api/vehicles
Accept: application/json



### Login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@example.com",
  "password": "password123"
}




### Create Booking Form
POST http://127.0.0.1:8000/api/booking-forms
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|lg85jRag4jmf23acbppqloSvpnDvWcJcHIhGECUCabc063d4

{
  "name": "Airport Transfers",
  "slug": "airport-transfers",
  "currency": "DKK",
  "services": ["distance", "hourly"],
  "settings": {
    "enable_waypoints": true,
    "min_distance_km": 5,
    "enable_vehicle_selection": true,
    "show_summary_sidebar": true
  }
}
