### Ping Test
GET http://127.0.0.1:8000/api/ping
Accept: application/json
#
###
GET http://127.0.0.1:8000/api/vehicles
Accept: application/json



### Login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "email": "test1@limoflux.com",
  "password": "password123"
}

###




POST http://127.0.0.1:8000/api/vehicles
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|95YoNupl1LGJBHyHwfzEsogNAV4NscyFTUqaJ61Uabf05986

{
  "vehicle_type_id": 1,
  "name": "Mercedes S-Class",
  "passengers": 3,
  "luggage": 2,
  "base_price": 150,
  "price_per_km": 3.5
}

